spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mos
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update

  web:
    resources:
      static-locations: file:uploads/
